font_family      JetBrainsMono Nerd Font
font_size        12
bold_font        auto
italic_font      auto
bold_italic_font auto
# Al presionar Ctrl+Shift+K se limpia la pantalla y el historial por completo
map ctrl+shift+k combine : clear_terminal scrollback active : send_text normal,application \x0c
background #1e1e2e
foreground #cdd6f4
selection_background #f5c2e7
selection_foreground #1e1e2e

cursor #cdd6f4
cursor_text_color #1e1e2e

url_color #89b4fa

black   #45475a
bright_black   #585b70
red     #f38ba8
bright_red     #f38ba8
green   #a6e3a1
bright_green   #a6e3a1
yellow  #f9e2af
bright_yellow  #f9e2af
blue    #89b4fa
bright_blue    #89b4fa
magenta #f5c2e7
bright_magenta #f5c2e7
cyan    #94e2d5
bright_cyan    #94e2d5
white   #bac2de
bright_white   #a6adc8

background_opacity 0.85
window_padding_width 12

shell_integration enabled
confirm_os_window_close 0

enable_audio_bell no
mouse_hide_wait 3.0
tab_bar_style powerline
active_tab_foreground #cdd6f4
inactive_tab_foreground #6c7086
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 8.0

map ctrl+shift+v paste_from_clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+n new_os_window
map ctrl+shift+t new_tab
map ctrl+shift+q close_window
