[ColorScheme]
author=Catppuccin
label=Catppuccin Mocha

[Color:Active]
BackgroundNormal=#1e1e2e
BackgroundAlternate=#181825
BackgroundButton=#313244
BackgroundDark=#11111b
ForegroundNormal=#cdd6f4
ForegroundButton=#cdd6f4
ForegroundInactive=#6c7086
ForegroundSelected=#cdd6f4
ForegroundLink=#89b4fa
ForegroundVisited=#cba6f7
DecorationHover=#cba6f7
DecorationFocus=#cba6f7
DecorationFocusSecondary=#a6adc8

[Color:Inactive]
BackgroundNormal=#1e1e2e
BackgroundAlternate=#181825
BackgroundButton=#313244
BackgroundDark=#11111b
ForegroundNormal=#6c7086
ForegroundButton=#6c7086
ForegroundInactive=#45475a
ForegroundSelected=#6c7086
ForegroundLink=#89b4fa
ForegroundVisited=#cba6f7
DecorationHover=#cba6f7
DecorationFocus=#cba6f7
DecorationFocusSecondary=#a6adc8

[Color:Disabled]
BackgroundNormal=#1e1e2e
BackgroundAlternate=#181825
BackgroundButton=#313244
BackgroundDark=#11111b
ForegroundNormal=#45475a
ForegroundButton=#45475a
ForegroundInactive=#313244
ForegroundSelected=#45475a
ForegroundLink=#89b4fa
ForegroundVisited=#cba6f7
DecorationHover=#cba6f7
DecorationFocus=#cba6f7
DecorationFocusSecondary=#a6adc8

[Selection]
BackgroundNormal=#cba6f7
ForegroundNormal=#1e1e2e
BackgroundAlternate=#b4befe
ForegroundAlternate=#1e1e2e

[General]
ColorGroup=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff)
