[Options]
autostart=true
check_clipboard=true
color_alt_background=#181825
color_background=#1e1e2e
color_foreground=#cdd6f4
color_selection_background=#cba6f7
color_selection_foreground=#1e1e2e
color_tab_foreground=#6c7086
color_tab_indicator=#cba6f7
font=JetBrainsMono Nerd Font, 12
history_dialog_shortcut=Ctrl+Shift+V
max_items=500
style=Fusion
tabs=&portapapeles
